###Test service document
http://localhost:4004/odata/v4/CatalogService/
 
###Get service metadata
http://localhost:4004/odata/v4/CatalogService/$metadata
 
###Get all the Purchase orders
http://localhost:4004/odata/v4/CatalogService/POs
 
###Get Order by key
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC3A052
 
###Get PO data with pagination
http://localhost:4004/odata/v4/CatalogService/POs?$top=2&$skip=2
 
###Get PO data with filter
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$filter=bankName eq 'My Bank of San Francisco'
 
###Case sensitive filter
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$filter=contains(nameFirst,'Jo')
 
###Load dependent data
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC3A052?$expand=Items

###Insert data to database
POST http://localhost:4004/odata/v4/CatalogService/EmployeeSet
Content-Type: application/json
 
{
      "nameFirst": "Anubhav",
      "nameMiddle": null,
      "nameLast": "Oberoy",
      "nameInitials": null,
      "sex": "M",
      "language": "E",
      "phoneNumber": null,
      "email": "contact@anubhavtrainings.com",
      "loginName": "OBEROYAB",
      "Currency_code": "USD",
      "salaryAmount": 76239,
      "accountNumber": "9988776655",
      "bankId": "12100",
      "bankName": "My Bank of San Francisco"
}